lessons:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "lessons_dev"
      threads: 32
      timeout_seconds: 300
      location: US